#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

set -e

echo ""
echo "=================================="
echo "=Start install..."
echo "=" 
echo "=Bootstrap installs things..."
echo "="
echo "="
echo "="
echo "="
echo "="
echo "="
echo "="
echo "="
echo "="
echo "=================================="
echo ""

. ./pkg/shell/log.sh
. ./pkg/shell/os.sh
. ./pkg/shell/link.sh

declare __oo__lsb_dist
LSBDist

install_homebrew () {
  if test ! $(which brew)
  then
    echo "Installing Homebrew for you..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

install_ohmyzsh () {
  if [ ! -d ~/.oh-my-zsh ]
  then
    info 'installing oh-my-zsh'
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false
  for src in $(find "$DOTFILES_ROOT/" -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_ohmyzsh
install_dotfiles

if [[ ${__oo__lsb_dist} == "macos" ]]
then
    echo "macos: start .dotfile bootstraps"
    install_homebrew
    info "installing dependencies"
    if source bin/dot
    then
      success "dependencies installed"
    else
      fail "error installing dependencies"
    fi
elif [[ ${__oo__lsb_dist} = "ubuntu" ]]
then
    echo "ubuntu"
    BASE_DIR=`pwd`
    # 建立gitconfig链接
    echo "配置Git..."
    git config --global user.name "dubuqingfeng"
    git config --global user.email 1135326346@qq.com
    # 建立terminator配置链接
    echo "配置terminator..."
    # mkdir -p $HOME/.config/terminator
    # if [ -L $HOME/.config/terminator/config ];then
    #     unlink $HOME/.config/terminator/config
    # elif [ -f $HOME/.config/terminator/config ];then
    #     mv $HOME/.config/terminator/config $HOME/.config/terminator/config.$TODAY
    # fi
    # ln -s $BASE_DIR/terminator/config $HOME/.config/terminator/config
fi

echo ''
echo '  All installed!'
